function [pos_L_sw] = Left_Swing_Foot_Position(q)
import casadi.*
[xbar,zbar,rotY,q1R,q2R,q1L,q2L] = deal(q(1),q(2),q(3),q(4),q(5),q(6),q(7));

pos_L_sw = [xbar+(2/5).*(1+(-1).*cos(q2L)).*(cos(rotY).*sin(q1L)+cos(q1L).* ...
  sin(rotY))+(-2/5).*sin(q2L).*(cos(q1L).*cos(rotY)+(-1).*sin(q1L) ...
  .*sin(rotY))+(4/5).*(cos(q2L).*(cos(rotY).*sin(q1L)+cos(q1L).* ...
  sin(rotY))+sin(q2L).*(cos(q1L).*cos(rotY)+(-1).*sin(q1L).*sin( ...
  rotY))),zbar+(-2/5).*sin(q2L).*((-1).*cos(rotY).*sin(q1L)+(-1).* ...
  cos(q1L).*sin(rotY))+(2/5).*(1+(-1).*cos(q2L)).*(cos(q1L).*cos( ...
  rotY)+(-1).*sin(q1L).*sin(rotY))+(4/5).*(sin(q2L).*((-1).*cos( ...
  rotY).*sin(q1L)+(-1).*cos(q1L).*sin(rotY))+cos(q2L).*(cos(q1L).* ...
  cos(rotY)+(-1).*sin(q1L).*sin(rotY)))];
end

