function a_cassie = a_func(kx,ky,ufp_sol_x,ufp_sol_y,s_cl,z_cl,p_st_to_sw_z_init)
%A_FUNC
%    A_CASSIE = A_FUNC(KX,KY,UFP_SOL_X,UFP_SOL_Y,S_CL,Z_CL,P_ST_TO_SW_Z_INIT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:31:16

a_cassie = z_cl./(s_cl-1.0)-(-p_st_to_sw_z_init+z_cl+kx.*ufp_sol_x+ky.*ufp_sol_y)./s_cl;
