function b_cassie = b_func(kx,ky,ufp_sol_x,ufp_sol_y,s_cl,z_cl,p_st_to_sw_z_init)
%B_FUNC
%    B_CASSIE = B_FUNC(KX,KY,UFP_SOL_X,UFP_SOL_Y,S_CL,Z_CL,P_ST_TO_SW_Z_INIT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:31:16

t2 = s_cl.^2;
b_cassie = -(-p_st_to_sw_z_init+z_cl+kx.*ufp_sol_x+ky.*ufp_sol_y+p_st_to_sw_z_init.*t2-kx.*t2.*ufp_sol_x-ky.*t2.*ufp_sol_y)./(s_cl.*(s_cl-1.0));
