function [posR] = ...
    Right_Stance_Foot_Position(xb,zb,rotYb,q1R,q2R,q1L,q2L)
import casadi.*

posR = [xb+(2/5).*(1+(-1).*cos(q2R)).*(cos(rotYb).*sin(q1R)+cos(q1R).* ...
  sin(rotYb))+(-2/5).*sin(q2R).*(cos(q1R).*cos(rotYb)+(-1).*sin(q1R) ...
  .*sin(rotYb))+(4/5).*(cos(q2R).*(cos(rotYb).*sin(q1R)+cos(q1R).* ...
  sin(rotYb))+sin(q2R).*(cos(q1R).*cos(rotYb)+(-1).*sin(q1R).*sin( ...
  rotYb))),0,zb+(-2/5).*sin(q2R).*((-1).*cos(rotYb).*sin(q1R)+(-1).* ...
  cos(q1R).*sin(rotYb))+(2/5).*(1+(-1).*cos(q2R)).*(cos(q1R).*cos( ...
  rotYb)+(-1).*sin(q1R).*sin(rotYb))+(4/5).*(sin(q2R).*((-1).*cos( ...
  rotYb).*sin(q1R)+(-1).*cos(q1R).*sin(rotYb))+cos(q2R).*(cos(q1R).* ...
  cos(rotYb)+(-1).*sin(q1R).*sin(rotYb)))];

posR = posR([1,3]);
end

