function [Jac_L_sw] = Left_Swing_Foot_Jacobian(xb,zb,rotYb,q1R,q2R,q1L,q2L)

Jac_L_sw = [1,0,(-2/5).*sin(q2L).*((-1).*cos(rotYb).*sin(q1L)+(-1).*cos(q1L) ...
  .*sin(rotYb))+(2/5).*(1+(-1).*cos(q2L)).*(cos(q1L).*cos(rotYb)+( ...
  -1).*sin(q1L).*sin(rotYb))+(4/5).*(sin(q2L).*((-1).*cos(rotYb).* ...
  sin(q1L)+(-1).*cos(q1L).*sin(rotYb))+cos(q2L).*(cos(q1L).*cos( ...
  rotYb)+(-1).*sin(q1L).*sin(rotYb))),0,0,(-2/5).*sin(q2L).*((-1).* ...
  cos(rotYb).*sin(q1L)+(-1).*cos(q1L).*sin(rotYb))+(2/5).*(1+(-1).* ...
  cos(q2L)).*(cos(q1L).*cos(rotYb)+(-1).*sin(q1L).*sin(rotYb))+(4/5) ...
  .*(sin(q2L).*((-1).*cos(rotYb).*sin(q1L)+(-1).*cos(q1L).*sin( ...
  rotYb))+cos(q2L).*(cos(q1L).*cos(rotYb)+(-1).*sin(q1L).*sin(rotYb) ...
  )),(2/5).*sin(q2L).*(cos(rotYb).*sin(q1L)+cos(q1L).*sin(rotYb))+( ...
  -2/5).*cos(q2L).*(cos(q1L).*cos(rotYb)+(-1).*sin(q1L).*sin(rotYb)) ...
  +(4/5).*((-1).*sin(q2L).*(cos(rotYb).*sin(q1L)+cos(q1L).*sin( ...
  rotYb))+cos(q2L).*(cos(q1L).*cos(rotYb)+(-1).*sin(q1L).*sin(rotYb) ...
  ));0,1,(2/5).*(1+(-1).*cos(q2L)).*((-1).*cos(rotYb).*sin(q1L)+(-1) ...
  .*cos(q1L).*sin(rotYb))+(-2/5).*sin(q2L).*((-1).*cos(q1L).*cos( ...
  rotYb)+sin(q1L).*sin(rotYb))+(4/5).*(cos(q2L).*((-1).*cos(rotYb).* ...
  sin(q1L)+(-1).*cos(q1L).*sin(rotYb))+sin(q2L).*((-1).*cos(q1L).* ...
  cos(rotYb)+sin(q1L).*sin(rotYb))),0,0,(2/5).*(1+(-1).*cos(q2L)).*( ...
  (-1).*cos(rotYb).*sin(q1L)+(-1).*cos(q1L).*sin(rotYb))+(-2/5).* ...
  sin(q2L).*((-1).*cos(q1L).*cos(rotYb)+sin(q1L).*sin(rotYb))+(4/5) ...
  .*(cos(q2L).*((-1).*cos(rotYb).*sin(q1L)+(-1).*cos(q1L).*sin( ...
  rotYb))+sin(q2L).*((-1).*cos(q1L).*cos(rotYb)+sin(q1L).*sin(rotYb) ...
  )),(-2/5).*cos(q2L).*((-1).*cos(rotYb).*sin(q1L)+(-1).*cos(q1L).* ...
  sin(rotYb))+(2/5).*sin(q2L).*(cos(q1L).*cos(rotYb)+(-1).*sin(q1L) ...
  .*sin(rotYb))+(4/5).*(cos(q2L).*((-1).*cos(rotYb).*sin(q1L)+(-1).* ...
  cos(q1L).*sin(rotYb))+(-1).*sin(q2L).*(cos(q1L).*cos(rotYb)+(-1).* ...
  sin(q1L).*sin(rotYb)))];
end

